apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "qbooks.fullname" . }}-admin
  labels:
    {{- include "qbooks.labels" . | nindent 4 }}
spec:
  {{- if not .Values.admin.autoscaling.enabled }}
  replicas: {{ .Values.admin.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "admin.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.admin.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "admin.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.admin.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "qbooks.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.admin.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.admin.securityContext | nindent 12 }}
          image: "{{ .Values.admin.image.repository }}:{{ .Values.admin.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.admin.image.pullPolicy }}
          command: ["/bin/sh", "-c"]
          args: ["python manage.py collectstatic --no-input && python manage.py runserver 0.0.0.0:{{ .Values.admin.port}}"]
          envFrom:
            - configMapRef:
                name: {{ include "qbooks.fullname" . }}-configs
            - secretRef:
                name: {{ include "qbooks.fullname" . }}-secrets
          ports:
            - name: http
              containerPort: {{ .Values.admin.port }}
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: http
          readinessProbe:
            tcpSocket:
              port: http
          resources:
            {{- toYaml .Values.admin.resources | nindent 12 }}
      {{- with .Values.admin.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.admin.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.admin.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
