version: "3.8"
services:

  api_gateway:
    build:
      context: .
      dockerfile: api_gateway/Dockerfile
    environment:
        MICROSERVICES_HOST: "microservices"
        MICROSERVICES_PORT: 50051
        FLASK_ENV: "development"
    image: api_gateway
    networks:
      - catalog
    ports:
      - "5000:5000"
    volumes:
      - ./api_gateway:/opt/api_gateway
      - ./common:/opt/api_gateway/common

  catalog:
    build:
      context: .
      dockerfile: microservices/Dockerfile
    image: microservices
    networks:
      - catalog
    volumes:
      - ./microservices:/opt/microservices
      - ./common:/opt/microservices/common

  catalog-admin:
    build:
      context: .
      dockerfile: microservices/Dockerfile.admin
    image: catalog-admin
    networks:
      - catalog
    ports:
      - "50000:50000"
    volumes:
      - ./microservices:/opt/microservices
      - ./common:/opt/microservices/common

networks:
  catalog:
