version: "3.8"
services:

  nginx:
    image: "nginx:1.19.8"
    restart: always
    networks:
      - catalog
    ports:
      - "80:80"
    volumes:
      - ./compose/nginx/nginx.conf:/etc/nginx/nginx.conf

  rabbit:
    image: "rabbitmq:3.9-management-alpine"
    ports:
      - "15672:15672"
    networks:
      - catalog

  api-gateway:
    build:
      context: ./api_gateway/
    restart: always
    environment:
        CATALOG_HOST: "catalog"
        CATALOG_PORT: 50051
        RECOMENDATOR_HOST: "recomendator"
        RECOMENDATOR_PORT: 50051
        RECOMENDATOR_ASYNC_HOST: "recomendator-async"
        RECOMENDATOR_ASYNC_PORT: 50051
        FLASK_ENV: "development"
    networks:
      - catalog
    volumes:
      - ./api_gateway:/opt/api_gateway
      - ./common:/usr/local/lib/python3.8/site-packages/common

  catalog:
    build:
      context: ./catalog/
    restart: always
    env_file:
      - compose.env
    networks:
      - catalog
    volumes:
      - ./catalog:/opt/catalog
      - ./common:/usr/local/lib/python3.8/site-packages/common
    depends_on:
      - db

  catalog-admin:
    build:
      context: ./catalog/
    command: ["python", "manage.py", "runserver", "0.0.0.0:50051"]
    restart: always
    env_file:
      - compose.env
    networks:
      - catalog
    volumes:
      - ./catalog:/opt/catalog
      - ./common:/usr/local/lib/python3.8/site-packages/common
    depends_on:
      - db

  recomendator:
    build:
      context: recomendator/
      dockerfile: Dockerfile
    restart: always
    env_file:
      - compose.env
    networks:
      - catalog
    environment:
      CATALOG_HOST: "catalog"
      CATALOG_PORT: 50051
    volumes:
      - ./recomendator:/opt/recomendator
      - ./common:/usr/local/lib/python3.8/site-packages/common
    depends_on:
      - recomendator_db

  recomendator-async:
    build:
      context: recomendator-async
      dockerfile: Dockerfile
    restart: always
    env_file:
      - compose.env
    networks:
      - catalog
    volumes:
      - ./recomendator-async:/opt/recomendator
      - ./common:/opt/recomendator/common

  recomendator-db:
    image: "postgres:11"
    restart: always
    env_file:
      - compose.env
    networks:
      - catalog

  recomendator-async-db:
    image: "postgres:11"
    restart: always
    env_file:
      - compose.env
    networks:
      - catalog

  db:
    image: "postgres:11"
    restart: always
    env_file:
      - compose.env
    networks:
      - catalog
    
  recomendator_db:
    image: "postgres:11"
    restart: always
    env_file:
      - compose.env
    networks:
      - catalog

networks:
  catalog:
