version: "3.8"
services:

  nginx:
    image: "nginx:1.19.8"
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./compose/nginx/nginx.conf:/etc/nginx/nginx.conf

  frontend:
    build:
      context: ./frontend
    env_file:
      - ./frontend/.env.example
    volumes:
      - ./frontend/src:/app/src
    ports:
      - "3000:80"

  api-gateway:
    build:
      context: ./api_gateway/
    restart: always
    environment:
        CATALOG_HOST: "catalog"
        CATALOG_PORT: 50051
        RECOMENDATOR_HOST: "recomendator"
        RECOMENDATOR_PORT: 50051
        ACCOUNTS_HOST: "accounts"
        ACCOUNTS_PORT: 50051
        FLASK_ENV: "development"
    volumes:
      - ./api_gateway:/opt/api_gateway
      - ./common:/usr/local/lib/python3.8/site-packages/common

  catalog:
    build:
      context: ./catalog/
    restart: always
    env_file:
      - compose.env
    volumes:
      - ./catalog:/opt/catalog
      - ./common:/usr/local/lib/python3.8/site-packages/common
    depends_on:
      - db

  catalog-admin:
    build:
      context: ./catalog/
    command: ["python", "manage.py", "runserver", "0.0.0.0:50051"]
    restart: always
    env_file:
      - compose.env
    volumes:
      - ./catalog:/opt/catalog
      - ./common:/usr/local/lib/python3.8/site-packages/common
    depends_on:
      - db

  accounts:
    build:
      context: accounts
    restart: always
    networks:
      - catalog
    volumes:
      - ./accounts:/opt/accounts
      - ./common:/usr/local/lib/python3.8/site-packages/common

  recomendator:
    build:
      context: ./recomendator/
    restart: always
    env_file:
      - compose.env
    environment:
        CATALOG_HOST: "catalog"
        CATALOG_PORT: 50051
    volumes:
      - ./recomendator:/opt/recomendator
      - ./common:/usr/local/lib/python3.8/site-packages/common
    depends_on:
      - recomendator_db

  db:
    image: "postgres:11"
    restart: always
    env_file:
      - compose.env
    
  recomendator_db:
    image: "postgres:11"
    restart: always
    env_file:
      - compose.env

  accounts_db:
    image: "postgres:11"
