version: "3.8"
services:

  nginx:
    image: "nginx:1.19.8"
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./compose/nginx/nginx.conf:/etc/nginx/nginx.conf

  frontend:
    build:
      context: ./frontend
    env_file:
      - ./frontend/.env.example
    volumes:
      - ./frontend/src:/app/src
    ports:
      - "3000:80"

  api-gateway:
    build:
      context: ./api_gateway/
    restart: always
    environment:
        CATALOG_HOST: "catalog"
        CATALOG_PORT: 50051
        RECOMMENDATOR_HOST: "recommendator"
        RECOMMENDATOR_PORT: 50051
        FLASK_ENV: "development"
    volumes:
      - ./api_gateway:/opt/api_gateway
      - ./common:/usr/local/lib/python3.8/site-packages/common
    ports:
      - "80:5000"

  catalog:
    build:
      context: ./catalog/
    restart: always
    env_file:
      - compose_catalog.env
    volumes:
      - ./catalog:/opt/catalog
      - ./common:/usr/local/lib/python3.8/site-packages/common
    depends_on:
      - catalog-db

  catalog-admin:
    build:
      context: ./catalog/
    command: ["python", "manage.py", "runserver", "0.0.0.0:50051"]
    restart: always
    env_file:
      - compose_catalog.env
    volumes:
      - ./catalog:/opt/catalog
      - ./common:/usr/local/lib/python3.8/site-packages/common
    depends_on:
      - catalog-db

  recommendator:
    build:
      context: ./recommendator/
    restart: always
    env_file:
      - compose_recommendator.env
    environment:
        CATALOG_HOST: "catalog"
        CATALOG_PORT: 50051
    volumes:
      - ./recommendator:/opt/recommendator
      - ./common:/usr/local/lib/python3.8/site-packages/common
    depends_on:
      - recommendator-db

  catalog-db:
    image: "postgres:11"
    restart: always
    env_file:
      - compose_catalog.env
    
  recommendator-db:
    image: "postgres:11"
    restart: always
    env_file:
      - compose_recommendator.env

