version: "3.8"
services:

  api_gateway:
    build:
      context: api_gateway
    environment:
        MICROSERVICES_HOST: "microservices"
        MICROSERVICES_PORT: 50051
        FLASK_ENV: "development"
    image: api_gateway
    networks:
      - catalog
    ports:
      - "5000:5000"
    volumes:
      - ./api_gateway:/opt/api_gateway
      - ./common:/opt/api_gateway/common

  catalog:
    build:
      context: .
      dockerfile: catalog/Dockerfile
    image: catalog
    networks:
      - catalog
    volumes:
      - ./catalog:/opt/catalog
      - ./common:/opt/catalog/common

  catalog-admin:
    build:
      context: .
      dockerfile: catalog/Dockerfile.admin
    image: catalog-admin
    networks:
      - catalog
    ports:
      - "50000:50000"
    volumes:
      - ./catalog:/opt/catalog
      - ./common:/opt/catalog/common

networks:
  catalog:
