version: "3.8"
services:

  nginx:
    image: "nginx:1.19.8"
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./compose/nginx/nginx.conf:/etc/nginx/nginx.conf

  frontend:
    build:
      context: ./frontend
    env_file:
      - ./frontend/.env.example
    volumes:
      - ./frontend/src:/app/src
    ports:
      - "3000:80"

  api-gateway:
    build:
      context: ./api_gateway/
    restart: always
    environment:
        CATALOG_HOST: "catalog"
        CATALOG_PORT: 50051
        RECOMMENDATOR_HOST: "recommendator"
        RECOMMENDATOR_PORT: 50051
        ACCOUNTS_HOST: "accounts"
        ACCOUNTS_PORT: 50051
        FLASK_ENV: "development"
    volumes:
      - ./api_gateway:/opt/api_gateway
      - ./common:/usr/local/lib/python3.8/site-packages/common

  catalog:
    build:
      context: ./catalog/
    restart: always
    env_file:
      - compose_catalog.env
    volumes:
      - ./catalog:/opt/catalog
      - ./common:/usr/local/lib/python3.8/site-packages/common
    depends_on:
      - catalog-db

  catalog-admin:
    build:
      context: ./catalog/
    command: ["python", "manage.py", "runserver", "0.0.0.0:50051"]
    restart: always
    env_file:
      - compose_catalog.env
    volumes:
      - ./catalog:/opt/catalog
      - ./common:/usr/local/lib/python3.8/site-packages/common
    depends_on:
      - catalog-db

  accounts:
    build:
      context: accounts
    restart: always
    env_file:
      - compose_accounts.env
    volumes:
      - ./accounts:/opt/accounts
      - ./common:/usr/local/lib/python3.8/site-packages/common

  recommendator:
    build:
      context: ./recommendator/
    restart: always
    env_file:
      - compose_recommendator.env
    environment:
        CATALOG_HOST: "catalog"
        CATALOG_PORT: 50051
    volumes:
      - ./recommendator:/opt/recommendator
      - ./common:/usr/local/lib/python3.8/site-packages/common
    depends_on:
      - recommendator-db

  locust-master:
    image: locustio/locust
    ports:
     - "8089:8089"
    volumes:
      - ./test_stress:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master -H http://locust-master:8089

  locust-worker:
    image: locustio/locust
    volumes:
      - ./test_stress:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host locust-master
    deploy:
      replicas: 2

  catalog-db:
    image: "postgres:11"
    restart: always
    env_file:
      - compose_catalog.env
    
  recommendator-db:
    image: "postgres:11"
    restart: always
    env_file:
      - compose_recommendator.env

  accounts-db:
    image: "postgres:11"
    restart: always
    env_file:
      - compose_accounts.env
