version: "3.8"
services:

  api_gateway:
    build:
      context: .
      dockerfile: api_gateway/Dockerfile
    environment:
        MICROSERVICES_HOST: "microservices"
        MICROSERVICES_PORT: 50051
        FLASK_ENV: "development"
    image: api_gateway
    networks:
      - microservices
    ports:
      - "5000:5000"
    volumes:
      - ./api_gateway:/opt/api_gateway
      - ./common:/opt/api_gateway/common

  microservices:
    build:
      context: .
      dockerfile: microservices/Dockerfile
    image: microservices
    networks:
      - microservices
    volumes:
      - ./microservices:/opt/microservices
      - ./common:/opt/microservices/common

networks:
  microservices:
