version: "3.8"
services:

  nginx:
    image: "nginx:1.19.8"
    restart: always
    networks:
      - catalog
    ports:
      - "80:80"
    volumes:
      - ./compose/nginx/nginx.conf:/etc/nginx/nginx.conf

  rabbit:
    image: "rabbitmq:3.9-management-alpine"
    ports:
      - "15672:15672"
    networks:
      - catalog

  api-gateway:
    build:
      context: .
      dockerfile: api_gateway/Dockerfile
    restart: always
    environment:
        CATALOG_HOST: "catalog"
        CATALOG_PORT: 50051
        FLASK_ENV: "development"
    networks:
      - catalog
    volumes:
      - ./api_gateway:/opt/api_gateway
      - ./common:/opt/api_gateway/common

  catalog:
    build:
      context: .
      dockerfile: catalog/Dockerfile
    restart: always
    env_file:
      - compose.env
    networks:
      - catalog
    volumes:
      - ./catalog:/opt/catalog
      - ./common:/opt/catalog/common
    depends_on:
      - db

  catalog-admin:
    build:
      context: .
      dockerfile: catalog/Dockerfile
    command: ["python", "manage.py", "runserver", "0.0.0.0:50051"]
    restart: always
    env_file:
      - compose.env
    networks:
      - catalog
    volumes:
      - ./catalog:/opt/catalog
      - ./common:/opt/catalog/common
    depends_on:
      - db

  db:
    image: "postgres:11"
    restart: always
    env_file:
      - compose.env
    networks:
      - catalog

networks:
  catalog:
