version: "3.8"
services:

  api_gateway:
    build:
      context: api_gateway
    restart: always
    environment:
        CATALOG_HOST: "catalog"
        CATALOG_PORT: 50051
        FLASK_ENV: "development"
    networks:
      - catalog
    ports:
      - "5000:5000"
    volumes:
      - ./api_gateway:/opt/api_gateway
      - ./common:/opt/api_gateway/common

  catalog:
    build:
      context: .
      dockerfile: catalog/Dockerfile
    restart: always
    env_file:
      - compose.env
    networks:
      - catalog
    ports:
      - "50051:50051"
    volumes:
      - ./catalog:/opt/catalog
      - ./common:/opt/catalog/common

  catalog-admin:
    build:
      context: .
      dockerfile: catalog/Dockerfile
    command: ["python", "manage.py", "runserver", "0.0.0.0:50051"]
    restart: always
    env_file:
      - compose.env
    networks:
      - catalog
    ports:
      - "50000:50051"
    volumes:
      - ./catalog:/opt/catalog
      - ./common:/opt/catalog/common

  db:
    image: "postgres:11"
    restart: always
    env_file:
      - compose.env
    networks:
      - catalog

networks:
  catalog:
