# Generated by Django 3.1.2 on 2021-11-23 14:23

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recomendations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='libraryuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='libraryuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='author',
            name='cqrs_revision',
        ),
        migrations.RemoveField(
            model_name='author',
            name='cqrs_updated',
        ),
        migrations.RemoveField(
            model_name='book',
            name='cqrs_revision',
        ),
        migrations.RemoveField(
            model_name='book',
            name='cqrs_updated',
        ),
        migrations.RemoveField(
            model_name='bookinstance',
            name='cqrs_revision',
        ),
        migrations.RemoveField(
            model_name='bookinstance',
            name='cqrs_updated',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='cqrs_revision',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='cqrs_updated',
        ),
        migrations.RemoveField(
            model_name='libraryuser',
            name='cqrs_revision',
        ),
        migrations.RemoveField(
            model_name='libraryuser',
            name='cqrs_updated',
        ),
    ]
