apiVersion: v1
kind: Secret
metadata:
  name: {{ include "catalog.fullname" . }}-recomendator-db-secrets
type: Opaque
stringData:
  POSTGRES_USERNAME: "{{ .Values.recomendatorDb.postgresqlUsername }}"
  POSTGRES_PASSWORD: "{{ .Values.recomendatorDb.postgresqlPassword }}"
