apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "qbooks.fullname" . }}-gateway
spec:
  selector:
    istio: ingress
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "qbooks.com"
