{{- if .Values.ingress.enabled -}}
{{- $fullName := include "catalog.fullname" . -}}
{{- $catalogPort := .Values.catalog.service.port -}}
{{- $adminPort := .Values.admin.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "catalog.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    - host: qbooks.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $catalogPort }}
          - path: /admin
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}-admin
                port:
                  number: {{ $adminPort }}
          - path: /static/admin
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}-admin
                port:
                  number: {{ $adminPort }}
{{- end }}

