FROM python:3.8

COPY catalog/requirements.txt /
RUN pip install -r requirements.txt

COPY catalog /opt/catalog
COPY common /opt/catalog/common
WORKDIR /opt/catalog

RUN python manage.py makemigrations
RUN python manage.py migrate
RUN python manage.py collectstatic

EXPOSE 50000
CMD [ "python", "manage.py", "runserver", "0.0.0.0:50000" ]