apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "catalog.fullname" . }}-api-gateway
  labels:
    {{- include "catalog.labels" . | nindent 4 }}
spec:
  {{- if not .Values.apiGateway.autoscaling.enabled }}
  replicas: {{ .Values.apiGateway.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "apiGateway.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.apiGateway.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "apiGateway.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.apiGateway.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "catalog.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.apiGateway.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.apiGateway.securityContext | nindent 12 }}
          image: "{{ .Values.apiGateway.image.repository }}:{{ .Values.apiGateway.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.apiGateway.image.pullPolicy }}
          command: ["/bin/sh", "-c"]
          args: ["flask run --host=0.0.0.0 --port={{ .Values.apiGateway.port}}"]
          env:
          - name: CATALOG_HOST
            value: "{{ include "catalog.fullname" . }}"
          - name: CATALOG_PORT
            value: "{{ .Values.catalog.service.port }}"
          - name: RECOMENDATOR_HOST
            value: "{{ include "catalog.fullname" . }}-recomendator"
          - name: RECOMENDATOR_PORT
            value: "{{ .Values.recomendator.service.port }}"
          - name: FLASK_ENV
            value: "{{ .Values.apiGateway.flaskEnv }}"
          ports:
            - name: http
              containerPort: {{ .Values.apiGateway.port }}
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: http
          readinessProbe:
            tcpSocket:
              port: http
          resources:
            {{- toYaml .Values.apiGateway.resources | nindent 12 }}
      {{- with .Values.apiGateway.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.apiGateway.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.apiGateway.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
