apiVersion: v1
kind: Service
metadata:
  name: {{ include "qbooks.fullname" . }}-api-gateway
  labels:
    {{- include "qbooks.labels" . | nindent 4 }}
spec:
  type: {{ .Values.apiGateway.service.type }}
  ports:
    - port: {{ .Values.apiGateway.service.port }}
      targetPort: {{ .Values.apiGateway.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "apiGateway.selectorLabels" . | nindent 4 }}
