# Generated by Django 3.1.2 on 2021-11-25 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LibraryUser',
        ),
    ]
