apiVersion: v1
kind: Service
metadata:
  name: {{ include "qbooks.fullname" . }}-frontend
  labels:
    {{- include "qbooks.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "frontend.selectorLabels" . | nindent 4 }}
