# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from common.pb2 import author_pb2 as catalog_dot_author__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class AuthorControllerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.List = channel.unary_stream(
        '/catalog.AuthorController/List',
        request_serializer=catalog_dot_author__pb2.AuthorListRequest.SerializeToString,
        response_deserializer=catalog_dot_author__pb2.Author.FromString,
        )
    self.Create = channel.unary_unary(
        '/catalog.AuthorController/Create',
        request_serializer=catalog_dot_author__pb2.Author.SerializeToString,
        response_deserializer=catalog_dot_author__pb2.Author.FromString,
        )
    self.Retrieve = channel.unary_unary(
        '/catalog.AuthorController/Retrieve',
        request_serializer=catalog_dot_author__pb2.AuthorRetrieveRequest.SerializeToString,
        response_deserializer=catalog_dot_author__pb2.Author.FromString,
        )
    self.Update = channel.unary_unary(
        '/catalog.AuthorController/Update',
        request_serializer=catalog_dot_author__pb2.Author.SerializeToString,
        response_deserializer=catalog_dot_author__pb2.Author.FromString,
        )
    self.Destroy = channel.unary_unary(
        '/catalog.AuthorController/Destroy',
        request_serializer=catalog_dot_author__pb2.Author.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )


class AuthorControllerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def List(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Create(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Retrieve(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Update(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Destroy(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AuthorControllerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'List': grpc.unary_stream_rpc_method_handler(
          servicer.List,
          request_deserializer=catalog_dot_author__pb2.AuthorListRequest.FromString,
          response_serializer=catalog_dot_author__pb2.Author.SerializeToString,
      ),
      'Create': grpc.unary_unary_rpc_method_handler(
          servicer.Create,
          request_deserializer=catalog_dot_author__pb2.Author.FromString,
          response_serializer=catalog_dot_author__pb2.Author.SerializeToString,
      ),
      'Retrieve': grpc.unary_unary_rpc_method_handler(
          servicer.Retrieve,
          request_deserializer=catalog_dot_author__pb2.AuthorRetrieveRequest.FromString,
          response_serializer=catalog_dot_author__pb2.Author.SerializeToString,
      ),
      'Update': grpc.unary_unary_rpc_method_handler(
          servicer.Update,
          request_deserializer=catalog_dot_author__pb2.Author.FromString,
          response_serializer=catalog_dot_author__pb2.Author.SerializeToString,
      ),
      'Destroy': grpc.unary_unary_rpc_method_handler(
          servicer.Destroy,
          request_deserializer=catalog_dot_author__pb2.Author.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'catalog.AuthorController', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
