# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: catalog/genre.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='catalog/genre.proto',
  package='catalog',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x13\x63\x61talog/genre.proto\x12\x07\x63\x61talog\"!\n\x05Genre\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\"\x12\n\x10GenreListRequest2H\n\x0fGenreController\x12\x35\n\x04List\x12\x19.catalog.GenreListRequest\x1a\x0e.catalog.Genre\"\x00\x30\x01\x62\x06proto3'
)




_GENRE = _descriptor.Descriptor(
  name='Genre',
  full_name='catalog.Genre',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='catalog.Genre.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='catalog.Genre.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=65,
)


_GENRELISTREQUEST = _descriptor.Descriptor(
  name='GenreListRequest',
  full_name='catalog.GenreListRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=85,
)

DESCRIPTOR.message_types_by_name['Genre'] = _GENRE
DESCRIPTOR.message_types_by_name['GenreListRequest'] = _GENRELISTREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Genre = _reflection.GeneratedProtocolMessageType('Genre', (_message.Message,), {
  'DESCRIPTOR' : _GENRE,
  '__module__' : 'catalog.genre_pb2'
  # @@protoc_insertion_point(class_scope:catalog.Genre)
  })
_sym_db.RegisterMessage(Genre)

GenreListRequest = _reflection.GeneratedProtocolMessageType('GenreListRequest', (_message.Message,), {
  'DESCRIPTOR' : _GENRELISTREQUEST,
  '__module__' : 'catalog.genre_pb2'
  # @@protoc_insertion_point(class_scope:catalog.GenreListRequest)
  })
_sym_db.RegisterMessage(GenreListRequest)



_GENRECONTROLLER = _descriptor.ServiceDescriptor(
  name='GenreController',
  full_name='catalog.GenreController',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=87,
  serialized_end=159,
  methods=[
  _descriptor.MethodDescriptor(
    name='List',
    full_name='catalog.GenreController.List',
    index=0,
    containing_service=None,
    input_type=_GENRELISTREQUEST,
    output_type=_GENRE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GENRECONTROLLER)

DESCRIPTOR.services_by_name['GenreController'] = _GENRECONTROLLER

# @@protoc_insertion_point(module_scope)
