# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from common.pb2 import language_pb2 as catalog_dot_language__pb2


class LanguageControllerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.List = channel.unary_stream(
        '/catalog.LanguageController/List',
        request_serializer=catalog_dot_language__pb2.LanguageListRequest.SerializeToString,
        response_deserializer=catalog_dot_language__pb2.Language.FromString,
        )


class LanguageControllerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def List(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_LanguageControllerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'List': grpc.unary_stream_rpc_method_handler(
          servicer.List,
          request_deserializer=catalog_dot_language__pb2.LanguageListRequest.FromString,
          response_serializer=catalog_dot_language__pb2.Language.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'catalog.LanguageController', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
