# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: recommendator/recommendations.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='recommendator/recommendations.proto',
  package='recommendator',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n#recommendator/recommendations.proto\x12\rrecommendator\"\x80\x01\n\x04\x42ook\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0c\n\x04isbn\x18\x03 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x04 \x01(\x05\x12\r\n\x05genre\x18\x05 \x03(\x05\x12\x0f\n\x07summary\x18\x06 \x01(\t\x12\x10\n\x08language\x18\x07 \x01(\x05\x12\r\n\x05image\x18\x08 \x01(\t\"$\n\x16RecommendationsRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x32\x63\n\x19RecommendationsController\x12\x46\n\x04List\x12%.recommendator.RecommendationsRequest\x1a\x13.recommendator.Book\"\x00\x30\x01\x62\x06proto3'
)




_BOOK = _descriptor.Descriptor(
  name='Book',
  full_name='recommendator.Book',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='recommendator.Book.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='title', full_name='recommendator.Book.title', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isbn', full_name='recommendator.Book.isbn', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='author', full_name='recommendator.Book.author', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='genre', full_name='recommendator.Book.genre', index=4,
      number=5, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='summary', full_name='recommendator.Book.summary', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='language', full_name='recommendator.Book.language', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image', full_name='recommendator.Book.image', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=183,
)


_RECOMMENDATIONSREQUEST = _descriptor.Descriptor(
  name='RecommendationsRequest',
  full_name='recommendator.RecommendationsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='recommendator.RecommendationsRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=185,
  serialized_end=221,
)

DESCRIPTOR.message_types_by_name['Book'] = _BOOK
DESCRIPTOR.message_types_by_name['RecommendationsRequest'] = _RECOMMENDATIONSREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Book = _reflection.GeneratedProtocolMessageType('Book', (_message.Message,), {
  'DESCRIPTOR' : _BOOK,
  '__module__' : 'recommendator.recommendations_pb2'
  # @@protoc_insertion_point(class_scope:recommendator.Book)
  })
_sym_db.RegisterMessage(Book)

RecommendationsRequest = _reflection.GeneratedProtocolMessageType('RecommendationsRequest', (_message.Message,), {
  'DESCRIPTOR' : _RECOMMENDATIONSREQUEST,
  '__module__' : 'recommendator.recommendations_pb2'
  # @@protoc_insertion_point(class_scope:recommendator.RecommendationsRequest)
  })
_sym_db.RegisterMessage(RecommendationsRequest)



_RECOMMENDATIONSCONTROLLER = _descriptor.ServiceDescriptor(
  name='RecommendationsController',
  full_name='recommendator.RecommendationsController',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=223,
  serialized_end=322,
  methods=[
  _descriptor.MethodDescriptor(
    name='List',
    full_name='recommendator.RecommendationsController.List',
    index=0,
    containing_service=None,
    input_type=_RECOMMENDATIONSREQUEST,
    output_type=_BOOK,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_RECOMMENDATIONSCONTROLLER)

DESCRIPTOR.services_by_name['RecommendationsController'] = _RECOMMENDATIONSCONTROLLER

# @@protoc_insertion_point(module_scope)
