# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from common.pb2 import recommendations_pb2 as recommendator_dot_recommendations__pb2


class RecommendationsControllerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.List = channel.unary_stream(
        '/recommendator.RecommendationsController/List',
        request_serializer=recommendator_dot_recommendations__pb2.RecommendationsRequest.SerializeToString,
        response_deserializer=recommendator_dot_recommendations__pb2.Book.FromString,
        )


class RecommendationsControllerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def List(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_RecommendationsControllerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'List': grpc.unary_stream_rpc_method_handler(
          servicer.List,
          request_deserializer=recommendator_dot_recommendations__pb2.RecommendationsRequest.FromString,
          response_serializer=recommendator_dot_recommendations__pb2.Book.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'recommendator.RecommendationsController', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
