apiVersion: v1
kind: Service
metadata:
  name: {{ include "catalog.fullname" . }}-recomendator
  labels:
    {{- include "catalog.labels" . | nindent 4 }}
spec:
  type: {{ .Values.recomendator.service.type }}
  ports:
    - port: {{ .Values.recomendator.service.port }}
      targetPort: {{ .Values.recomendator.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "recomendator.selectorLabels" . | nindent 4 }}
