# Generated by Django 3.1.2 on 2021-11-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_auto_20210302_0630'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
