# Generated by Django 3.1.2 on 2021-11-19 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_auto_20210302_0630'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='cqrs_revision',
            field=models.IntegerField(default=0, help_text="This field must be incremented on any model update. It's used to for CQRS sync."),
        ),
        migrations.AddField(
            model_name='author',
            name='cqrs_updated',
            field=models.DateTimeField(auto_now=True, help_text="This field must be incremented on every model update. It's used to for CQRS sync."),
        ),
    ]
