# Generated by Django 3.1.2 on 2021-11-22 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0029_auto_20211122_0917'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='libraryuser',
            options={},
        ),
        migrations.AlterModelManagers(
            name='libraryuser',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='libraryuser',
            name='cqrs_revision',
            field=models.IntegerField(default=0, help_text="This field must be incremented on any model update. It's used to for CQRS sync."),
        ),
        migrations.AddField(
            model_name='libraryuser',
            name='cqrs_updated',
            field=models.DateTimeField(auto_now=True, help_text="This field must be incremented on every model update. It's used to for CQRS sync."),
        ),
    ]
