FROM python:3.8

COPY microservices/requirements.txt /
RUN pip install -r requirements.txt

COPY microservices /opt/microservices
COPY common /opt/microservices/common
WORKDIR /opt/microservices

RUN python manage.py makemigrations
RUN python manage.py migrate
RUN python manage.py collectstatic

EXPOSE 50000
CMD [ "python", "manage.py", "runserver", "0.0.0.0:50000" ]